# ------------------------------------------------------
# Spezielle Parameter für den LEDNode
# ------------------------------------------------------
led_node:
  ros__parameters:
    log_level: DEBUG

    led_topic: "/led"
    led_type: "WS2812"
    led_num_pixels: 28
    led_brightness: 0.3
    led_default_timeout: 1500
    led_default_duration_on: 500
    led_default_duration_off: 500