# ------------------------------------------------------
# NAVIGATION spezifische Konfigurationen
# ------------------------------------------------------
navigation_node:
  ros__parameters:
    log_level: INFO
