# ------------------------------------------------------
# allgemeine Parameter die von allen Nodes genutzt
# werden können.
# ------------------------------------------------------
rover:
  ros__parameters:
    # ---- LEDs am rover
    # GPIO Pins so definieren, wie sie im ESP32 genutzt werden
    led_pin_turn_indicator: 18
    led_pin_lights: 19
    led_pin_break_light: 20

    # ---- Eingangs-Pins am EPS32
    #
    pin_in_ultrasonic: 21

