# ------------------------------------------------------
# Spezielle Parameter für den Sensor_Node
# ------------------------------------------------------
sensor_node:
  ros__parameters:
    #
    # Battery-Sensor liegt am I2C-Bus 
    battery_sample_refresh_hz: 0.1  # Angabe in Herz 0.1hz = alle 10sek
    battery_voltage_channel: 0
    battery_current_channel: 1
    battery_sensor_active: true
#    battery_critical: 12.4        # hier schaltet der rover ab, 4S, 4x 3.25V/Zelle
#    battery_low: 13.6             # unterste Spannung, Rover fährt noch 4x 3.4V/Zelle
    battery_full: 16.8            # 4S-Lipo 4x4.2V = 16.8V am Eingang des Voltage-Sensors

    # NUR FÜR TEST BEI 12 EINGANGS_SPANNUNG
    battery_critical: 11.0        # nur für Grenzen zu testen
    battery_low: 11.5             # nur für Grenzen zu testen
#    battery_full: 12.2           # nur für Grenzen zu testen

    #
    # Es wird ein einfacher VoltageSensor verwendet
    voltage_max_in: 25.0  # Maximaler Spannungseingang 25.0
    voltage_max_out: 5.0  # ADC Ausgang 0-5.0V (in 25.0V = out 5.0V)

    
    # IMU-Sensor liegt am I2C-Bus 1
    imu_sensor_active: false
    imu_sample_refresh_hz: 100  # Angabe in Herz 100hz
