# ------------------------------------------------------
# VISION  spezifische Konfigurationen
# ------------------------------------------------------
vision_node:
  ros__parameters:
    vison_topic: "/vision/result"
